### ISSUE TITLE
bug: disallow out-of-order timeline generation

### ISSUE THREAD

**Issue by jdbeightol** [jdbeightol/obsidian-simple-day-planner#3]
### Steps to Reproduce

Use the following agenda to reproduce this behavior.

```
- 08:00 start
- 18:00 end
- 12:00 lunch
```

The resulting timeline will show a block from 08:00 to 18:00 called `start`.  A ingle block at 18:00 called `<End of Plan>`, and then finally another block after 18:00 that claims to start at 12:00, but really starts at about 18:15, and then lasts for maybe 15 minutes-ish.

### Expected behavior
Out of order agenda items should be one of:
- re-ordered based on time
- an error! the timeline should not render

**Comment by csss1234** [comment]
Original Day Planner seems to have achieved this recently. See link:
https://github.com/lynchjames/obsidian-day-planner/pull/163

**Comment by jdbeightol** [comment]
Thanks for the heads up! I'm going to patch and test with that solution.
